asw13b/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from pdclone import views

urlpatterns = [
    path('', include('pdclone.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

pdclone/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.posts, name='posts'),
    path('create_posts/', views.create_posts,  name='create_posts'),
    path('communities/<str:filter>', views.communities),
    path('create_community/', views.create_community),
    path('login/', views.login),
    path('logout/', views.logout_view),
    path('u/<str:username>/<str:filter>/<str:orden>', views.user_view),
    path('c/<str:id>/<str:show>/<str:order>', views.community),
    path('edit_profile/', views.edit_profile),
    path('subscribe/<str:id>', views.subscribe),
    path('unsubscribe/<str:id>', views.unsubscribe),
    path('post/<int:post_id>/', views.post, name='single_post'),
    path('comments/', views.comments, name='comments'),
    path('comment/<int:comment_id>/upvote_comment', views.upvote_comment, name='upvote_comment'),
    path('comment/<int:comment_id>/downvote_comment', views.downvote_comment, name='downvote_comment'),
    path('post/<int:post_id>/upvote/<str:page>', views.upvote, name='upvote'),
    path('post/<int:post_id>/downvote/<str:page>', views.downvote, name='downvote'),
    path('post/<int:post_id>/create_comment/', views.create_comment, name='create_comment'),
    path('savecomment/<int:id>', views.saveComment, name='savecomment'),
    path('savepost/<int:id>', views.savePost, name='savepost'),
    path('comment/<int:post_id>/<int:comment_id>/reply', views.reply_comment, name='reply_comment'),
    path('comment/<int:post_id>/<int:comment_id>/edit', views.edit_comment, name='edit_comment'),
    path('comment/<int:post_id>/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
    path('editar_post/<int:post_id>', views.editar_post, name='editar_post'),
    path('post/order_post/<str:orden>/', views.order_post, name = 'order_post'),
    path('post/order_coment/<str:orden>/', views.order_coment, name = 'order_coment'),
    path('post_subscrit/<str:filter>', views.post_subscrit, name = 'post_subscrit'),
    path('coment_suscrit/<str:filter>', views.coment_suscrit, name = 'coment_suscrit'),
    path('eliminar_post/<int:post_id>/', views.eliminar_post, name='eliminar_post'),
    path('confirmar_eliminar_post/<int:post_id>/<int:page>/', views.confirmar_eliminar_post, name='confirmar_eliminar_post'),
    path('single_post/order_singlepost/<str:orden>/<int:post_id>/', views.order_singlepost, name = 'order_singlepost'),
    path('post/search_post/<str:search>/', views.order_post, name = 'search_post'), 

]

pdclone/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class CustomUser(models.Model):
    username = models.CharField(max_length=30, null=True)
    name = models.CharField(max_length=30, null=True)
    banner = models.ImageField(null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    created_date = models.DateTimeField(default=now, editable=False)
    description = models.CharField(default=" ", max_length=1000)


class Community(models.Model):
    id = models.CharField(max_length=30, primary_key=True)
    name = models.CharField(max_length=30, null=True, blank=True)
    banner = models.ImageField(null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    subscribers = models.ManyToManyField(CustomUser)

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default="", related_name="posts")
    body = models.CharField(max_length=1000)
    url = models.URLField(blank=True)
    community = models.ForeignKey(Community, on_delete=models.CASCADE, default="", related_name="posts")
    points = models.IntegerField(default=1)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    savedBy = models.ManyToManyField(CustomUser)

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default="", related_name="comments")
    body = models.CharField(max_length=1000)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    finalvotes = models.IntegerField(default=0)
    saved_by_user = models.BooleanField(default=False)
    savedBy = models.ManyToManyField(CustomUser)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)

pdclone/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import *
from django.contrib.auth.models import *
from .models import Community, CustomUser, Comment

class PostForm(forms.Form):
    url = forms.URLField(
        widget=forms.URLInput(attrs={'class': 'style-86'}),
        label='URL'
    )

    title = forms.CharField(
        max_length=200,
        widget=forms.Textarea(attrs={'class': 'style-98', 'required': 'true', 'rows': '1', 'minlength': '3', 'maxlength': '200'}),
        label='Title'
    )

    body = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'style-98-vis', 'required': 'true', 'rows': '4', 'minlength': '3', 'maxlength': '200'}),
        label='Body'
    )

    community = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'style-98', 'required': 'true', 'rows': '1', 'minlength': '1', 'maxlength': '200'}),
        label='Community'
    )

class EditPostForm(forms.Form):
    url = forms.URLField(
        widget=forms.URLInput(attrs={'class': 'style-86'}),
        label='URL'
    )

    title = forms.CharField(
        max_length=200,
        widget=forms.Textarea(attrs={'class': 'style-98', 'required': 'true', 'rows': '1', 'minlength': '3', 'maxlength': '200'}),
        label='Title'
    )

    body = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'style-98-vis', 'required': 'true', 'rows': '4', 'minlength': '3', 'maxlength': '200'}),
        label='Body'
    )

    community = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'style-98', 'required': 'true', 'rows': '1', 'minlength': '1', 'maxlength': '200'}),
        label='Community'
    )

class CommunityForm(ModelForm):
    class Meta:
        model= Community
        fields = ['id', 'name', 'banner', 'avatar']

class CustomUserForm(ModelForm):
    class Meta:
        model= CustomUser
        fields = ['name', 'avatar', 'banner', 'description']      

class CommentForm(forms.Form):
    body = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'style-98-vis', 'required': 'true', 'rows': '4', 'minlength': '3', 'maxlength': '200'}),
        label='Body'
    )

pdclone/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import logout
from .models import Post, Community, CustomUser, Comment
from .forms import CommunityForm, PostForm, CustomUserForm, CommentForm, EditPostForm
from django.db.models import Count
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def posts(request):
    queryset = request.GET.get("buscar")
    if queryset: posts = Post.objects.filter(title__contains= queryset)
    else:
        posts = Post.objects.all()
    context = {'posts':posts}
    return render(request, 'posts.html', context)

def create_posts(request):
    comunidad = None
    if request.method == 'POST':
        form = PostForm(request.POST)
        if not request.user.is_authenticated: return redirect('posts')
        if form.is_valid():
            # Crear la publicación si el formulario es válido
            if (request.user.is_authenticated):
                author = CustomUser.objects.get(username=request.user.username)
            try:
                comunidad = Community.objects.get(name=form.cleaned_data['community'])
            except Community.DoesNotExist:
                messages.error(request, 'La comunidad no existe. Por favor, introduce una comunidad válida.')
                
            if comunidad:    
                post = Post(
                    title=form.cleaned_data['title'],
                    body=form.cleaned_data['body'],
                    url=form.cleaned_data['url'],
                    author_id=author.id,
                    community=comunidad
                )
                post.save()
                return redirect('posts')
        else: return redirect('posts')    
    else:
        form = PostForm()  # Crear una instancia del formulario en caso de GET request

    return render(request, 'create_posts.html', {'form': form})

def communities(request, filter):
    allCommunities = Community.objects.all()
    if (request.user.is_authenticated):
        user = CustomUser.objects.get(username=request.user.username)
        communitiesSubscribed = user.community_set.all()

        if (filter == 'local'): communities = allCommunities
        elif (filter == 'suscrito'): communities = communitiesSubscribed
        else: return redirect('/')

        communities_subscribed = []
        for c in communities:
            posts = c.posts.all()
            numComments = 0
            for p in posts:
                numComments += p.comments.all().count()
            if c in communitiesSubscribed: communities_subscribed.append([c, True, posts.count(), numComments])
            else: communities_subscribed.append([c, False, posts.count(), numComments])  
        return render(request, 'communities.html', {'communities':communities_subscribed,
                                                    'local':(filter == 'local')})
    else:

        if (filter == 'local'): communities = allCommunities
        elif (filter == 'suscrito'): communities = Community.objects.none()
        else: return redirect('/')

        communities_subscribed = []
        for c in communities:
            posts = c.posts.all()
            numComments = 0
            for p in posts:
                numComments += p.comments.all().count()
            communities_subscribed.append([c, False, posts.count(), numComments])
        return render(request, 'communities.html', {'communities':communities_subscribed,
                                                    'local':(filter == 'local')})

def create_community(request):
    if (request.method == 'GET'):
        form = CommunityForm()
        return render(request, 'create_community.html', {'form': form})
    elif (request.method == 'POST'):
        
        form = CommunityForm(request.POST, request.FILES)
        if (form.is_valid()):
            form.save()
        return redirect('/communities/local')
    else:
        return render(request, 'create_community.html')

def login(request):
    if (request.user.is_authenticated):
        try:
            user = CustomUser.objects.get(username=request.user.username)
        except CustomUser.DoesNotExist:
            user = CustomUser(username=request.user.username, name=request.user.username)
            user.save()

    return redirect("/")

def logout_view(request):
    logout(request)
    return redirect("/")

def user_view(request, username, filter, orden):
    try:
        showPosts = True
        showComments = True
        showSaved = False
        if (filter == 'resumen'): 
            showPosts = showComments = True
            showSaved = False
        elif (filter == 'comentarios'): 
            showPosts = False
            showComments = True
            showSaved = False
        elif (filter == 'publicaciones'):
            showPosts = True
            showComments = False
            showSaved = False
        elif (filter == 'guardados'):
            if (not (request.user.is_authenticated and request.user.username == username)): return redirect('/')
            showPosts = showComments = False
            showSaved = True        
        else: return redirect('/')

        user = CustomUser.objects.get(username=username)
        posts = user.posts.all().order_by(orden)
        savedPosts = user.post_set.all().order_by(orden)
        if(orden == '-points'): orden = '-upvotes'
        comments = user.comments.all().order_by(orden)
        savedComments = user.comment_set.all().order_by(orden)
        return render(request, 'user.html', 
                      {'userL':user,
                       'showBanner':user.banner is not None and user.banner,
                       'showAvatar':user.avatar is not None and user.avatar,
                       'showName':(user.name != ' ' and user.name != ''),
                       'showDescription':(user.description != ' ' and user.description != ''),
                       'isUser': (request.user.is_authenticated and request.user.username == username),
                       'showPosts': showPosts,
                       'showComments': showComments,
                       'showSaved': showSaved,
                       'posts': posts,
                       'comments': comments,
                       'savedC': savedComments,
                       'savedP': savedPosts})
    except CustomUser.DoesNotExist:
        return redirect('/')  

def edit_profile(request):
    if (request.user.is_authenticated):
        try:
            user = CustomUser.objects.get(username=request.user.username)
        except CustomUser.DoesNotExist:
            return redirect('/') 
        
        if (request.method == 'GET'):
            form = CustomUserForm(instance=user)
            return render(request, 'edit_profile.html', {'user': user, 'form':form, 'isUser': request.user.is_authenticated})   
        elif (request.method == 'POST'):
            form = CustomUserForm(request.POST, request.FILES, instance=user)
            if (form.is_valid()):
                form.save()
            return redirect('/u/${request.user.username}/resumen/-created_date')
        else: return redirect('/')    
    else:
        return redirect('/')  

def subscribe(request, id):
    if (request.user.is_authenticated):
        community = Community.objects.get(id=id)
        user = CustomUser.objects.get(username=request.user.username)
        community.subscribers.add(user)
    return redirect("/communities/suscrito")

def unsubscribe(request, id):
    if (request.user.is_authenticated):
        community = Community.objects.get(id=id)
        user = CustomUser.objects.get(username=request.user.username)
        community.subscribers.remove(user)
    return redirect("/communities/suscrito")

def post(request, post_id):
    post = Post.objects.get(id=post_id)
    comments = post.comments.all()
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        print(form)
        if form.is_valid():
            # Crear la publicación si el formulario es válido
            if (request.user.is_authenticated):
                author = CustomUser.objects.get(username=request.user.username)
        
            comment = Comment(
                body=form.cleaned_data['body'],
                author_id=author.id,
                post=post_id
            )
            comment.save()
            print(comment)
    else:
        form = CommentForm()  # Crear una instancia del formulario en caso de GET request

    return render(request, 'single_post.html', {'post': post, 'comments': comments, "form": CommentForm()})

def community(request, id, show, order):
    try:
        community = Community.objects.get(id=id)
        posts = community.posts.all()
        data = Comment.objects.none()
        showPosts = False
        if (show == 'posts'): 
            showPosts = True
            data = posts
        elif (show == 'comments'): 
            showPosts = False
            for p in posts:
                comments = p.comments.all()
                data = data | comments

        else: return redirect('/communities/local')
        data = data.order_by(order)
        return render(request, 'community.html', {'community':community,
                                                'showBanner':community.banner is not None and community.banner,
                                                'showAvatar':community.avatar is not None and community.avatar,
                                                'showName':(community.name is not None and community.name != ''),
                                                'showPosts':showPosts,
                                                'data':data,
                                                'order': order})
    except Community.DoesNotExist: 
        return redirect('/communities/local')

def comments(request):
    queryset = request.GET.get("buscar")

pdclone/templates/communities.html
{% extends "navigation.html" %}
{% block content %} 
    <div class="mt-4 p-0 fl-1">
        <div tabindex="-1">
            <div class="communities container-lg">
                <div>
                    <h1 class="h4 mb-4">Lista de comunidades</h1>
                    <div class="row g-2 justify-content-between">
                        <div class="col-auto">
                            <div class="listing-type-select btn-group btn-group-toggle flex-wrap" role="group">
                                {% if local %}
                                    <a class="btn btn-outline-secondary" id="listing-type-input-yUSaxMZvyqII3mW15N9f-subscribed" href="/communities/suscrito">Suscrito</a>
                                    <a class="btn btn-outline-secondary active" id="listing-type-input-yUSaxMZvyqII3mW15N9f-local" href="/communities/local">Local</a>
                                {% else %}
                                    <a class="btn btn-outline-secondary active" id="listing-type-input-yUSaxMZvyqII3mW15N9f-subscribed" href="/communities/suscrito">Suscrito</a>
                                    <a class="btn btn-outline-secondary" id="listing-type-input-yUSaxMZvyqII3mW15N9f-local" href="/communities/local">Local</a>
                                {% endif %}
                              </div>
                        </div>
                        <div class="col-auto">
                                <div class="col-auto"><label class="visually-hidden" for="communities-search">Crear comunidad</label>
                                    
                                    <a href ="/create_community" class="btn btn-secondary"><span>Crear comunidad</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-sm table-hover" id="community_table">
                                <thead class="pointer">
                                    <tr>
                                        <th>Nombre</th>
                                        <th class="text-right">Suscriptores</th>
                                        <th class="text-right d-none d-lg-table-cell">Publicaciones</th>
                                        <th class="text-right d-none d-lg-table-cell">Comentarios</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                {% for community in communities %}
                                    <tbody>
                                        <tr>
                                            <td>
                                                <a class="community-link " title="!{{community.0.name}}" href="/c/{{community.0.id}}/posts/created_date">
                                                    {% if community.0.avatar is not None and community.0.avatar %}
                                                    <img class="overflow-hidden pictrs-image object-fit-cover img-icon me-1" src="{{community.0.avatar.url}}" alt="" title="" loading="lazy">
                                                    {% endif %}
                                                    <span class="overflow-wrap-anywhere">{{community.0.name}}</span>
                                                </a>
                                            </td>
                                            <td class="text-right">{{community.0.subscribers.count}}</td>
                                            <td class="text-right d-none d-lg-table-cell">{{community.2}}</td>
                                            <td class="text-right d-none d-lg-table-cell">{{community.3}}</td>
                                            <td class="text-right">
                                                {% if user.is_authenticated %}
                                                    {% if community.1 %}
                                                    <button class="btn btn-link d-inline-block"><a href="/unsubscribe/{{community.0.id}}">Desuscribirse</a></button>
                                                    {% else %}
                                                    <button class="btn btn-link d-inline-block"><a href="/subscribe/{{community.0.id}}">Suscribirse</a></button>
                                                    {% endif %}
                                                {% else %}
                                                <button class="btn btn-link d-inline-block" disabled>Suscribirse</button>
                                                {% endif %}
                                                
                                            </td>
                                        </tr>
                                    </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</html>
{% endblock %}

pdclone/templates/confirmar_eliminar_post_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminación</title>
    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="../../../static/single_post.css" />
  
    <!-- Current theme and more -->
    <link data-inferno-helmet="true" rel="stylesheet" type="text/css" href="../../../static/litely.css" id="default-light" media="(prefers-color-scheme: light)">
    <link data-inferno-helmet="true" rel="stylesheet" type="text/css" href="../../../static/darkly.css" id="default-dark" media="(prefers-color-scheme: no-preference), (prefers-color-scheme: dark)">

</head>
<body style="text-align: center; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh;">
    <h1 class="style-102">Confirmar Eliminación</h1>
    <p>¿Estás seguro de que quieres eliminar el post "{{ post.title }}"?</p>
    <form class="style-269vis" method="post" action="{% url 'eliminar_post' post.id %}">
        {% csrf_token %}
        <button class="style-243vis" type="submit">Sí, eliminar</button>
        <a class="style-243vis2" href="{% url 'single_post' post.id%}">Cancelar</a>
    </form>
</body>
</html>

pdclone/templates/confirmar_eliminar_post_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminación</title>
    <!-- Styles -->
    <link rel="stylesheet" type="text/css" href="../../../static/single_post.css" />
  
    <!-- Current theme and more -->
    <link data-inferno-helmet="true" rel="stylesheet" type="text/css" href="../../../static/litely.css" id="default-light" media="(prefers-color-scheme: light)">
    <link data-inferno-helmet="true" rel="stylesheet" type="text/css" href="../../../static/darkly.css" id="default-dark" media="(prefers-color-scheme: no-preference), (prefers-color-scheme: dark)">

</head>
<body style="text-align: center; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh;">
    <h1 class="style-102">Confirmar Eliminación</h1>
    <p>¿Estás seguro de que quieres eliminar el post "{{ post.title }}"?</p>
    <form class="style-269vis" method="post" action="{% url 'eliminar_post' post.id %}">
        {% csrf_token %}
        <button class="style-243vis" type="submit">Sí, eliminar</button>
        <a class="style-243vis2" href="{% url 'posts' %}">Cancelar</a>
    </form>
</body>
</html>

pdclone/templates/create_community.html
{% extends "navigation.html" %}
{% block content %}
        <div class="mt-4 p-0 fl-1">
        <div tabindex="-1">
            <div class="create-post container-lg">
                <div class="row">
                    <div class="col-12 col-lg-6 offset-lg-3 mb-4" id="createPostForm">
                        <h1 class="h4 mb-4">Crear comunidad</h1>
                        <form class="" method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            
                            <button class="btn btn-secondary me-2" type="submit">Crear</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}                   
                     

pdclone/templates/edit_comment.html
{%extends "navigation.html"%}
{% block content %}
<div class="style-268">
    <form class="style-269" method="post" action="{% url 'edit_comment' comment.post.id comment.id %}">
        {% csrf_token %}
        <p>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Edit Comment</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" name="body" cols="40" rows="4"
                 required="" minlength="3" maxlength="200" id="id_body">{{ comment.body }}</textarea>
            </div>
        </p>
        <div class="style-270">
            <div class="style-350">
                <div class="style-355"></div><input class="btn btn-primary btn-block" type="submit" value="Edit">
            </div>
        </div>
    </form>
</div>
{% endblock %}